name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
      - run: npm i
        working-directory: ./
      - run: npm run build
        working-directory: ./
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/portfolio-website
            git pull origin master
            git status
            npm install
            npm run build
            cp -r build/* /var/www/portfolio-website/client
